version: '3.8'

services:
  # Laravel Service
  laravel:
    build:
      context: ./laravel
    container_name: laravel_app
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=laravel
      - DB_USERNAME=root
      - DB_PASSWORD=root
    volumes:
      - ./laravel:/var/www/html
    depends_on:
      - mysql
    networks:
      - app-network

  # Nginx Service
  nginx:
    image: nginx:alpine
    container_name: nginx_app
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./laravel:/var/www/html
    ports:
      - "80:80"
    depends_on:
      - laravel
    networks:
      - app-network

  # MySQL Service
  mysql:
    image: mysql:5.7
    container_name: mysql_app
    environment:
      MYSQL_ROOT_PASSWORD: root  # Correct usage of root user credentials
      MYSQL_DATABASE: laravel
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - app-network

  # Random HTTP Service (Optional)
  random_service:
    image: hashicorp/http-echo
    container_name: random_service
    command: ["-text='This is the random HTTP service response'"]
    profiles:
      - random
    networks:
      - app-network

volumes:
  mysql-data:

networks:
  app-network:
    driver: bridge
